FROM n8nio/n8n:latest

ENV NODE_ENV=production
ENV N8N_PORT=10000
ENV N8N_PROTOCOL=https
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV GENERIC_TIMEZONE=America/New_York
ENV TZ=America/New_York
ENV EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
ENV EXECUTIONS_DATA_SAVE_ON_ERROR=all
ENV EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true

RUN mkdir -p /home/node/.n8n

EXPOSE 10000

CMD ["/usr/local/bin/n8n", "start"]
